from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.loadButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadButton.setGeometry(QtCore.QRect(10, 10, 93, 28))
        self.loadButton.setObjectName("loadButton")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(110, 10, 93, 28))
        self.saveButton.setObjectName("saveButton")
        self.describeButton = QtWidgets.QPushButton(self.centralwidget)
        self.describeButton.setGeometry(QtCore.QRect(210, 10, 93, 28))
        self.describeButton.setObjectName("describeButton")
        self.histButton = QtWidgets.QPushButton(self.centralwidget)
        self.histButton.setGeometry(QtCore.QRect(310, 10, 93, 28))
        self.histButton.setObjectName("histButton")
        self.barButton = QtWidgets.QPushButton(self.centralwidget)
        self.barButton.setGeometry(QtCore.QRect(410, 10, 93, 28))
        self.barButton.setObjectName("barButton")
        self.scatterButton = QtWidgets.QPushButton(self.centralwidget)
        self.scatterButton.setGeometry(QtCore.QRect(510, 10, 93, 28))
        self.scatterButton.setObjectName("scatterButton")
        self.boxButton = QtWidgets.QPushButton(self.centralwidget)
        self.boxButton.setGeometry(QtCore.QRect(610, 10, 93, 28))
        self.boxButton.setObjectName("boxButton")
        self.crossTabButton = QtWidgets.QPushButton(self.centralwidget)
        self.crossTabButton.setGeometry(QtCore.QRect(710, 10, 93, 28))
        self.crossTabButton.setObjectName("crossTabButton")
        self.resetButton = QtWidgets.QPushButton(self.centralwidget)
        self.resetButton.setGeometry(QtCore.QRect(810, 10, 93, 28))
        self.resetButton.setObjectName("resetButton")
        self.columnListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.columnListWidget.setGeometry(QtCore.QRect(10, 50, 256, 192))
        self.columnListWidget.setObjectName("columnListWidget")
        self.plotDropArea = QtWidgets.QFrame(self.centralwidget)
        self.plotDropArea.setGeometry(QtCore.QRect(300, 50, 641, 192))
        self.plotDropArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plotDropArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plotDropArea.setObjectName("plotDropArea")
        self.crosstabTable = QtWidgets.QTableWidget(self.centralwidget)
        self.crosstabTable.setGeometry(QtCore.QRect(10, 260, 931, 500))
        self.crosstabTable.setObjectName("crosstabTable")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Application"))
        self.loadButton.setText(_translate("MainWindow", "Load Data"))
        self.saveButton.setText(_translate("MainWindow", "Save Data"))
        self.describeButton.setText(_translate("MainWindow", "Describe Data"))
        self.histButton.setText(_translate("MainWindow", "Histogram"))
        self.barButton.setText(_translate("MainWindow", "Bar Plot"))
        self.scatterButton.setText(_translate("MainWindow", "Scatter Plot"))
        self.boxButton.setText(_translate("MainWindow", "Box Plot"))
        self.crossTabButton.setText(_translate("MainWindow", "Cross Tab"))
        self.resetButton.setText(_translate("MainWindow", "Reset"))